package com.clinbrain.mapper;

import com.clinbrain.model.ClassPropertyDefine;

import java.util.List;

public interface ClassPropertyDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_property_define
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_property_define
     *
     * @mbg.generated
     */
    int insert(ClassPropertyDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_property_define
     *
     * @mbg.generated
     */
    int insertSelective(ClassPropertyDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_property_define
     *
     * @mbg.generated
     */
    ClassPropertyDefine selectByPrimaryKey(Integer id);

    /**
     * get all class property define
     * @return
     */
    List<ClassPropertyDefine> selectAllClassPropertyDefine();

    /**
     * get all class property define of ds id
     * @param dsId
     * @return
     */
    List<ClassPropertyDefine> selectAllByDsId(Integer dsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_property_define
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ClassPropertyDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_property_define
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClassPropertyDefine record);
}