package com.clinbrain.mapper;

import com.clinbrain.model.DataTable;

import java.util.List;

public interface DataTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_table
     *
     * @mbg.generated
     */
    int insert(DataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_table
     *
     * @mbg.generated
     */
    int insertSelective(DataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_table
     *
     * @mbg.generated
     */
    DataTable selectByPrimaryKey(Integer id);

    /**
     * get all data table
     * @return
     */
    List<DataTable> selectAllDataTable();

    /**
     * get all data table by ds id
     * @param dsId
     * @return
     */
    List<DataTable> selectAllByDsId(Integer dsId);

    /**
     * get all data table by status
     * @return
     */
    List<DataTable> selectAllByStatus();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataTable record);
}