package com.clinbrain.mapper;

import com.clinbrain.model.EtlPartitionConf;

import java.util.List;

public interface EtlPartitionConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_histable_partitions_configuration
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_histable_partitions_configuration
     *
     * @mbg.generated
     */
    int insert(EtlPartitionConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_histable_partitions_configuration
     *
     * @mbg.generated
     */
    int insertSelective(EtlPartitionConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_histable_partitions_configuration
     *
     * @mbg.generated
     */
    EtlPartitionConf selectByPrimaryKey(Integer id);

    /**
     * get all etl table partition conf
     * @return
     */
    List<EtlPartitionConf> selectAllPartitionConf();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_histable_partitions_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EtlPartitionConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etl_histable_partitions_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EtlPartitionConf record);
}