package com.clinbrain.mapper;

import com.clinbrain.model.ParseLogs;

public interface ParseLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logs
     *
     * @mbg.generated
     */
    int insert(ParseLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logs
     *
     * @mbg.generated
     */
    int insertSelective(ParseLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logs
     *
     * @mbg.generated
     */
    ParseLogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logs
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ParseLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ParseLogs record);
}