package com.clinbrain.mapper;

import com.clinbrain.model.ParseLogDetails;

public interface ParseLogDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logdetails
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logdetails
     *
     * @mbg.generated
     */
    int insert(ParseLogDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logdetails
     *
     * @mbg.generated
     */
    int insertSelective(ParseLogDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logdetails
     *
     * @mbg.generated
     */
    ParseLogDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logdetails
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ParseLogDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logdetails
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ParseLogDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restore_data_logdetails
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ParseLogDetails record);
}