package com.clinbrain.mapper;

import com.clinbrain.model.TableMeta;

import java.util.List;

public interface TableMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table_meta
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table_meta
     *
     * @mbg.generated
     */
    int insert(TableMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table_meta
     *
     * @mbg.generated
     */
    int insertSelective(TableMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table_meta
     *
     * @mbg.generated
     */
    TableMeta selectByPrimaryKey(Integer id);

    /**
     * get all table meta
     * @return
     */
    List<TableMeta> selectAllTableMeta();

    /**
     * get all table meta by ds id
     * @param dsId
     * @return
     */
    List<TableMeta> selectAllByDsId(Integer dsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table_meta
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TableMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_table_meta
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TableMeta record);
}