package com.clinbrain.model;

import java.util.Date;

public class ClassStorageDefine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.ds_id
     *
     * @mbg.generated
     */
    private Integer dsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.storage_id
     *
     * @mbg.generated
     */
    private String storageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.storage_name
     *
     * @mbg.generated
     */
    private String storageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.sql_rowid_name
     *
     * @mbg.generated
     */
    private String sqlRowidName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.sql_child_sub
     *
     * @mbg.generated
     */
    private String sqlChildSub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.data_location
     *
     * @mbg.generated
     */
    private String dataLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.stream_location
     *
     * @mbg.generated
     */
    private String streamLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.global_name
     *
     * @mbg.generated
     */
    private String globalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.storage_type
     *
     * @mbg.generated
     */
    private String storageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_storage_define.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.id
     *
     * @return the value of t_class_storage_define.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.id
     *
     * @param id the value for t_class_storage_define.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.ds_id
     *
     * @return the value of t_class_storage_define.ds_id
     *
     * @mbg.generated
     */
    public Integer getDsId() {
        return dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.ds_id
     *
     * @param dsId the value for t_class_storage_define.ds_id
     *
     * @mbg.generated
     */
    public void setDsId(Integer dsId) {
        this.dsId = dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.class_name
     *
     * @return the value of t_class_storage_define.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.class_name
     *
     * @param className the value for t_class_storage_define.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.storage_id
     *
     * @return the value of t_class_storage_define.storage_id
     *
     * @mbg.generated
     */
    public String getStorageId() {
        return storageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.storage_id
     *
     * @param storageId the value for t_class_storage_define.storage_id
     *
     * @mbg.generated
     */
    public void setStorageId(String storageId) {
        this.storageId = storageId == null ? null : storageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.storage_name
     *
     * @return the value of t_class_storage_define.storage_name
     *
     * @mbg.generated
     */
    public String getStorageName() {
        return storageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.storage_name
     *
     * @param storageName the value for t_class_storage_define.storage_name
     *
     * @mbg.generated
     */
    public void setStorageName(String storageName) {
        this.storageName = storageName == null ? null : storageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.sql_rowid_name
     *
     * @return the value of t_class_storage_define.sql_rowid_name
     *
     * @mbg.generated
     */
    public String getSqlRowidName() {
        return sqlRowidName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.sql_rowid_name
     *
     * @param sqlRowidName the value for t_class_storage_define.sql_rowid_name
     *
     * @mbg.generated
     */
    public void setSqlRowidName(String sqlRowidName) {
        this.sqlRowidName = sqlRowidName == null ? null : sqlRowidName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.sql_child_sub
     *
     * @return the value of t_class_storage_define.sql_child_sub
     *
     * @mbg.generated
     */
    public String getSqlChildSub() {
        return sqlChildSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.sql_child_sub
     *
     * @param sqlChildSub the value for t_class_storage_define.sql_child_sub
     *
     * @mbg.generated
     */
    public void setSqlChildSub(String sqlChildSub) {
        this.sqlChildSub = sqlChildSub == null ? null : sqlChildSub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.data_location
     *
     * @return the value of t_class_storage_define.data_location
     *
     * @mbg.generated
     */
    public String getDataLocation() {
        return dataLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.data_location
     *
     * @param dataLocation the value for t_class_storage_define.data_location
     *
     * @mbg.generated
     */
    public void setDataLocation(String dataLocation) {
        this.dataLocation = dataLocation == null ? null : dataLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.stream_location
     *
     * @return the value of t_class_storage_define.stream_location
     *
     * @mbg.generated
     */
    public String getStreamLocation() {
        return streamLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.stream_location
     *
     * @param streamLocation the value for t_class_storage_define.stream_location
     *
     * @mbg.generated
     */
    public void setStreamLocation(String streamLocation) {
        this.streamLocation = streamLocation == null ? null : streamLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.global_name
     *
     * @return the value of t_class_storage_define.global_name
     *
     * @mbg.generated
     */
    public String getGlobalName() {
        return globalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.global_name
     *
     * @param globalName the value for t_class_storage_define.global_name
     *
     * @mbg.generated
     */
    public void setGlobalName(String globalName) {
        this.globalName = globalName == null ? null : globalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.storage_type
     *
     * @return the value of t_class_storage_define.storage_type
     *
     * @mbg.generated
     */
    public String getStorageType() {
        return storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.storage_type
     *
     * @param storageType the value for t_class_storage_define.storage_type
     *
     * @mbg.generated
     */
    public void setStorageType(String storageType) {
        this.storageType = storageType == null ? null : storageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_storage_define.create_time
     *
     * @return the value of t_class_storage_define.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_storage_define.create_time
     *
     * @param createTime the value for t_class_storage_define.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}