package com.clinbrain.model;

import java.util.Date;

public class ClassPropertyDefine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.ds_id
     *
     * @mbg.generated
     */
    private Integer dsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.class_id
     *
     * @mbg.generated
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.property_name
     *
     * @mbg.generated
     */
    private String propertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.property_collection
     *
     * @mbg.generated
     */
    private String propertyCollection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.property_aliases
     *
     * @mbg.generated
     */
    private String propertyAliases;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.property_calculated
     *
     * @mbg.generated
     */
    private String propertyCalculated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.property_cardinality
     *
     * @mbg.generated
     */
    private String propertyCardinality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.runtime_type
     *
     * @mbg.generated
     */
    private String runtimeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.sql_field_name
     *
     * @mbg.generated
     */
    private String sqlFieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.sql_list_type
     *
     * @mbg.generated
     */
    private String sqlListType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.sql_list_delimiter
     *
     * @mbg.generated
     */
    private String sqlListDelimiter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.storable
     *
     * @mbg.generated
     */
    private String storable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.storage_name
     *
     * @mbg.generated
     */
    private String storageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.storage_delimiter
     *
     * @mbg.generated
     */
    private String storageDelimiter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.storage_subscript
     *
     * @mbg.generated
     */
    private String storageSubscript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.storage_piece
     *
     * @mbg.generated
     */
    private String storagePiece;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_property_define.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.id
     *
     * @return the value of t_class_property_define.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.id
     *
     * @param id the value for t_class_property_define.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.ds_id
     *
     * @return the value of t_class_property_define.ds_id
     *
     * @mbg.generated
     */
    public Integer getDsId() {
        return dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.ds_id
     *
     * @param dsId the value for t_class_property_define.ds_id
     *
     * @mbg.generated
     */
    public void setDsId(Integer dsId) {
        this.dsId = dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.class_id
     *
     * @return the value of t_class_property_define.class_id
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.class_id
     *
     * @param classId the value for t_class_property_define.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.class_name
     *
     * @return the value of t_class_property_define.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.class_name
     *
     * @param className the value for t_class_property_define.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.property_name
     *
     * @return the value of t_class_property_define.property_name
     *
     * @mbg.generated
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.property_name
     *
     * @param propertyName the value for t_class_property_define.property_name
     *
     * @mbg.generated
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.property_collection
     *
     * @return the value of t_class_property_define.property_collection
     *
     * @mbg.generated
     */
    public String getPropertyCollection() {
        return propertyCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.property_collection
     *
     * @param propertyCollection the value for t_class_property_define.property_collection
     *
     * @mbg.generated
     */
    public void setPropertyCollection(String propertyCollection) {
        this.propertyCollection = propertyCollection == null ? null : propertyCollection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.property_aliases
     *
     * @return the value of t_class_property_define.property_aliases
     *
     * @mbg.generated
     */
    public String getPropertyAliases() {
        return propertyAliases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.property_aliases
     *
     * @param propertyAliases the value for t_class_property_define.property_aliases
     *
     * @mbg.generated
     */
    public void setPropertyAliases(String propertyAliases) {
        this.propertyAliases = propertyAliases == null ? null : propertyAliases.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.property_calculated
     *
     * @return the value of t_class_property_define.property_calculated
     *
     * @mbg.generated
     */
    public String getPropertyCalculated() {
        return propertyCalculated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.property_calculated
     *
     * @param propertyCalculated the value for t_class_property_define.property_calculated
     *
     * @mbg.generated
     */
    public void setPropertyCalculated(String propertyCalculated) {
        this.propertyCalculated = propertyCalculated == null ? null : propertyCalculated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.property_cardinality
     *
     * @return the value of t_class_property_define.property_cardinality
     *
     * @mbg.generated
     */
    public String getPropertyCardinality() {
        return propertyCardinality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.property_cardinality
     *
     * @param propertyCardinality the value for t_class_property_define.property_cardinality
     *
     * @mbg.generated
     */
    public void setPropertyCardinality(String propertyCardinality) {
        this.propertyCardinality = propertyCardinality == null ? null : propertyCardinality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.runtime_type
     *
     * @return the value of t_class_property_define.runtime_type
     *
     * @mbg.generated
     */
    public String getRuntimeType() {
        return runtimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.runtime_type
     *
     * @param runtimeType the value for t_class_property_define.runtime_type
     *
     * @mbg.generated
     */
    public void setRuntimeType(String runtimeType) {
        this.runtimeType = runtimeType == null ? null : runtimeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.sql_field_name
     *
     * @return the value of t_class_property_define.sql_field_name
     *
     * @mbg.generated
     */
    public String getSqlFieldName() {
        return sqlFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.sql_field_name
     *
     * @param sqlFieldName the value for t_class_property_define.sql_field_name
     *
     * @mbg.generated
     */
    public void setSqlFieldName(String sqlFieldName) {
        this.sqlFieldName = sqlFieldName == null ? null : sqlFieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.sql_list_type
     *
     * @return the value of t_class_property_define.sql_list_type
     *
     * @mbg.generated
     */
    public String getSqlListType() {
        return sqlListType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.sql_list_type
     *
     * @param sqlListType the value for t_class_property_define.sql_list_type
     *
     * @mbg.generated
     */
    public void setSqlListType(String sqlListType) {
        this.sqlListType = sqlListType == null ? null : sqlListType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.sql_list_delimiter
     *
     * @return the value of t_class_property_define.sql_list_delimiter
     *
     * @mbg.generated
     */
    public String getSqlListDelimiter() {
        return sqlListDelimiter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.sql_list_delimiter
     *
     * @param sqlListDelimiter the value for t_class_property_define.sql_list_delimiter
     *
     * @mbg.generated
     */
    public void setSqlListDelimiter(String sqlListDelimiter) {
        this.sqlListDelimiter = sqlListDelimiter == null ? null : sqlListDelimiter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.storable
     *
     * @return the value of t_class_property_define.storable
     *
     * @mbg.generated
     */
    public String getStorable() {
        return storable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.storable
     *
     * @param storable the value for t_class_property_define.storable
     *
     * @mbg.generated
     */
    public void setStorable(String storable) {
        this.storable = storable == null ? null : storable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.storage_name
     *
     * @return the value of t_class_property_define.storage_name
     *
     * @mbg.generated
     */
    public String getStorageName() {
        return storageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.storage_name
     *
     * @param storageName the value for t_class_property_define.storage_name
     *
     * @mbg.generated
     */
    public void setStorageName(String storageName) {
        this.storageName = storageName == null ? null : storageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.storage_delimiter
     *
     * @return the value of t_class_property_define.storage_delimiter
     *
     * @mbg.generated
     */
    public String getStorageDelimiter() {
        return storageDelimiter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.storage_delimiter
     *
     * @param storageDelimiter the value for t_class_property_define.storage_delimiter
     *
     * @mbg.generated
     */
    public void setStorageDelimiter(String storageDelimiter) {
        this.storageDelimiter = storageDelimiter == null ? null : storageDelimiter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.storage_subscript
     *
     * @return the value of t_class_property_define.storage_subscript
     *
     * @mbg.generated
     */
    public String getStorageSubscript() {
        return storageSubscript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.storage_subscript
     *
     * @param storageSubscript the value for t_class_property_define.storage_subscript
     *
     * @mbg.generated
     */
    public void setStorageSubscript(String storageSubscript) {
        this.storageSubscript = storageSubscript == null ? null : storageSubscript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.storage_piece
     *
     * @return the value of t_class_property_define.storage_piece
     *
     * @mbg.generated
     */
    public String getStoragePiece() {
        return storagePiece;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.storage_piece
     *
     * @param storagePiece the value for t_class_property_define.storage_piece
     *
     * @mbg.generated
     */
    public void setStoragePiece(String storagePiece) {
        this.storagePiece = storagePiece == null ? null : storagePiece.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_property_define.create_time
     *
     * @return the value of t_class_property_define.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_property_define.create_time
     *
     * @param createTime the value for t_class_property_define.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}