package com.clinbrain.model;

import java.util.Date;

public class DataSchema {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_schema.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_schema.ds_id
     *
     * @mbg.generated
     */
    private Integer dsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_schema.schema_name
     *
     * @mbg.generated
     */
    private String schemaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_schema.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_schema.src_topic
     *
     * @mbg.generated
     */
    private String srcTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_schema.target_topic
     *
     * @mbg.generated
     */
    private String targetTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_schema.db_vip
     *
     * @mbg.generated
     */
    private String dbVip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_schema.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_schema.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_schema.id
     *
     * @return the value of t_data_schema.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_schema.id
     *
     * @param id the value for t_data_schema.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_schema.ds_id
     *
     * @return the value of t_data_schema.ds_id
     *
     * @mbg.generated
     */
    public Integer getDsId() {
        return dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_schema.ds_id
     *
     * @param dsId the value for t_data_schema.ds_id
     *
     * @mbg.generated
     */
    public void setDsId(Integer dsId) {
        this.dsId = dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_schema.schema_name
     *
     * @return the value of t_data_schema.schema_name
     *
     * @mbg.generated
     */
    public String getSchemaName() {
        return schemaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_schema.schema_name
     *
     * @param schemaName the value for t_data_schema.schema_name
     *
     * @mbg.generated
     */
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName == null ? null : schemaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_schema.status
     *
     * @return the value of t_data_schema.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_schema.status
     *
     * @param status the value for t_data_schema.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_schema.src_topic
     *
     * @return the value of t_data_schema.src_topic
     *
     * @mbg.generated
     */
    public String getSrcTopic() {
        return srcTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_schema.src_topic
     *
     * @param srcTopic the value for t_data_schema.src_topic
     *
     * @mbg.generated
     */
    public void setSrcTopic(String srcTopic) {
        this.srcTopic = srcTopic == null ? null : srcTopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_schema.target_topic
     *
     * @return the value of t_data_schema.target_topic
     *
     * @mbg.generated
     */
    public String getTargetTopic() {
        return targetTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_schema.target_topic
     *
     * @param targetTopic the value for t_data_schema.target_topic
     *
     * @mbg.generated
     */
    public void setTargetTopic(String targetTopic) {
        this.targetTopic = targetTopic == null ? null : targetTopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_schema.db_vip
     *
     * @return the value of t_data_schema.db_vip
     *
     * @mbg.generated
     */
    public String getDbVip() {
        return dbVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_schema.db_vip
     *
     * @param dbVip the value for t_data_schema.db_vip
     *
     * @mbg.generated
     */
    public void setDbVip(String dbVip) {
        this.dbVip = dbVip == null ? null : dbVip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_schema.create_time
     *
     * @return the value of t_data_schema.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_schema.create_time
     *
     * @param createTime the value for t_data_schema.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_schema.description
     *
     * @return the value of t_data_schema.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_schema.description
     *
     * @param description the value for t_data_schema.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}