package com.clinbrain.model;

import java.util.Date;

public class StorageSubscriptDefine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_subscript_define.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_subscript_define.ds_id
     *
     * @mbg.generated
     */
    private Integer dsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_subscript_define.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_subscript_define.storage_name
     *
     * @mbg.generated
     */
    private String storageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_subscript_define.access_type
     *
     * @mbg.generated
     */
    private String accessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_subscript_define.expression
     *
     * @mbg.generated
     */
    private String expression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_subscript_define.is_rowid
     *
     * @mbg.generated
     */
    private Integer isRowid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_subscript_define.sort_id
     *
     * @mbg.generated
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_storage_subscript_define.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_subscript_define.id
     *
     * @return the value of t_storage_subscript_define.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage_subscript_define.id
     *
     * @param id the value for t_storage_subscript_define.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_subscript_define.ds_id
     *
     * @return the value of t_storage_subscript_define.ds_id
     *
     * @mbg.generated
     */
    public Integer getDsId() {
        return dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage_subscript_define.ds_id
     *
     * @param dsId the value for t_storage_subscript_define.ds_id
     *
     * @mbg.generated
     */
    public void setDsId(Integer dsId) {
        this.dsId = dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_subscript_define.class_name
     *
     * @return the value of t_storage_subscript_define.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage_subscript_define.class_name
     *
     * @param className the value for t_storage_subscript_define.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_subscript_define.storage_name
     *
     * @return the value of t_storage_subscript_define.storage_name
     *
     * @mbg.generated
     */
    public String getStorageName() {
        return storageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage_subscript_define.storage_name
     *
     * @param storageName the value for t_storage_subscript_define.storage_name
     *
     * @mbg.generated
     */
    public void setStorageName(String storageName) {
        this.storageName = storageName == null ? null : storageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_subscript_define.access_type
     *
     * @return the value of t_storage_subscript_define.access_type
     *
     * @mbg.generated
     */
    public String getAccessType() {
        return accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage_subscript_define.access_type
     *
     * @param accessType the value for t_storage_subscript_define.access_type
     *
     * @mbg.generated
     */
    public void setAccessType(String accessType) {
        this.accessType = accessType == null ? null : accessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_subscript_define.expression
     *
     * @return the value of t_storage_subscript_define.expression
     *
     * @mbg.generated
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage_subscript_define.expression
     *
     * @param expression the value for t_storage_subscript_define.expression
     *
     * @mbg.generated
     */
    public void setExpression(String expression) {
        this.expression = expression == null ? null : expression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_subscript_define.is_rowid
     *
     * @return the value of t_storage_subscript_define.is_rowid
     *
     * @mbg.generated
     */
    public Integer getIsRowid() {
        return isRowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage_subscript_define.is_rowid
     *
     * @param isRowid the value for t_storage_subscript_define.is_rowid
     *
     * @mbg.generated
     */
    public void setIsRowid(Integer isRowid) {
        this.isRowid = isRowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_subscript_define.sort_id
     *
     * @return the value of t_storage_subscript_define.sort_id
     *
     * @mbg.generated
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage_subscript_define.sort_id
     *
     * @param sortId the value for t_storage_subscript_define.sort_id
     *
     * @mbg.generated
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_storage_subscript_define.create_time
     *
     * @return the value of t_storage_subscript_define.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_storage_subscript_define.create_time
     *
     * @param createTime the value for t_storage_subscript_define.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}