package com.clinbrain.model;

import java.util.Date;

public class ClassDefine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.ver_id
     *
     * @mbg.generated
     */
    private Integer verId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.ds_id
     *
     * @mbg.generated
     */
    private Integer dsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.class_type
     *
     * @mbg.generated
     */
    private String classType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.client_data_type
     *
     * @mbg.generated
     */
    private String clientDataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.class_super
     *
     * @mbg.generated
     */
    private String classSuper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.sql_rowid_private
     *
     * @mbg.generated
     */
    private String sqlRowidPrivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.compile_namespace
     *
     * @mbg.generated
     */
    private String compileNamespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.runtime_type
     *
     * @mbg.generated
     */
    private String runtimeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.time_changed
     *
     * @mbg.generated
     */
    private Integer timeChanged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.time_created
     *
     * @mbg.generated
     */
    private Integer timeCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_define.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.id
     *
     * @return the value of t_class_define.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.id
     *
     * @param id the value for t_class_define.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.ver_id
     *
     * @return the value of t_class_define.ver_id
     *
     * @mbg.generated
     */
    public Integer getVerId() {
        return verId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.ver_id
     *
     * @param verId the value for t_class_define.ver_id
     *
     * @mbg.generated
     */
    public void setVerId(Integer verId) {
        this.verId = verId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.ds_id
     *
     * @return the value of t_class_define.ds_id
     *
     * @mbg.generated
     */
    public Integer getDsId() {
        return dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.ds_id
     *
     * @param dsId the value for t_class_define.ds_id
     *
     * @mbg.generated
     */
    public void setDsId(Integer dsId) {
        this.dsId = dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.class_name
     *
     * @return the value of t_class_define.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.class_name
     *
     * @param className the value for t_class_define.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.class_type
     *
     * @return the value of t_class_define.class_type
     *
     * @mbg.generated
     */
    public String getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.class_type
     *
     * @param classType the value for t_class_define.class_type
     *
     * @mbg.generated
     */
    public void setClassType(String classType) {
        this.classType = classType == null ? null : classType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.client_data_type
     *
     * @return the value of t_class_define.client_data_type
     *
     * @mbg.generated
     */
    public String getClientDataType() {
        return clientDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.client_data_type
     *
     * @param clientDataType the value for t_class_define.client_data_type
     *
     * @mbg.generated
     */
    public void setClientDataType(String clientDataType) {
        this.clientDataType = clientDataType == null ? null : clientDataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.class_super
     *
     * @return the value of t_class_define.class_super
     *
     * @mbg.generated
     */
    public String getClassSuper() {
        return classSuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.class_super
     *
     * @param classSuper the value for t_class_define.class_super
     *
     * @mbg.generated
     */
    public void setClassSuper(String classSuper) {
        this.classSuper = classSuper == null ? null : classSuper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.sql_rowid_private
     *
     * @return the value of t_class_define.sql_rowid_private
     *
     * @mbg.generated
     */
    public String getSqlRowidPrivate() {
        return sqlRowidPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.sql_rowid_private
     *
     * @param sqlRowidPrivate the value for t_class_define.sql_rowid_private
     *
     * @mbg.generated
     */
    public void setSqlRowidPrivate(String sqlRowidPrivate) {
        this.sqlRowidPrivate = sqlRowidPrivate == null ? null : sqlRowidPrivate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.compile_namespace
     *
     * @return the value of t_class_define.compile_namespace
     *
     * @mbg.generated
     */
    public String getCompileNamespace() {
        return compileNamespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.compile_namespace
     *
     * @param compileNamespace the value for t_class_define.compile_namespace
     *
     * @mbg.generated
     */
    public void setCompileNamespace(String compileNamespace) {
        this.compileNamespace = compileNamespace == null ? null : compileNamespace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.runtime_type
     *
     * @return the value of t_class_define.runtime_type
     *
     * @mbg.generated
     */
    public String getRuntimeType() {
        return runtimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.runtime_type
     *
     * @param runtimeType the value for t_class_define.runtime_type
     *
     * @mbg.generated
     */
    public void setRuntimeType(String runtimeType) {
        this.runtimeType = runtimeType == null ? null : runtimeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.time_changed
     *
     * @return the value of t_class_define.time_changed
     *
     * @mbg.generated
     */
    public Integer getTimeChanged() {
        return timeChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.time_changed
     *
     * @param timeChanged the value for t_class_define.time_changed
     *
     * @mbg.generated
     */
    public void setTimeChanged(Integer timeChanged) {
        this.timeChanged = timeChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.time_created
     *
     * @return the value of t_class_define.time_created
     *
     * @mbg.generated
     */
    public Integer getTimeCreated() {
        return timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.time_created
     *
     * @param timeCreated the value for t_class_define.time_created
     *
     * @mbg.generated
     */
    public void setTimeCreated(Integer timeCreated) {
        this.timeCreated = timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_define.create_time
     *
     * @return the value of t_class_define.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_define.create_time
     *
     * @param createTime the value for t_class_define.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}