package com.clinbrain.model;

import java.util.Date;

public class JournalOffset {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_offset.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_offset.journal_file_path
     *
     * @mbg.generated
     */
    private String journalFilePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_offset.journal_file_index
     *
     * @mbg.generated
     */
    private String journalFileIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_offset.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_journal_offset.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_offset.id
     *
     * @return the value of t_journal_offset.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_offset.id
     *
     * @param id the value for t_journal_offset.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_offset.journal_file_path
     *
     * @return the value of t_journal_offset.journal_file_path
     *
     * @mbg.generated
     */
    public String getJournalFilePath() {
        return journalFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_offset.journal_file_path
     *
     * @param journalFilePath the value for t_journal_offset.journal_file_path
     *
     * @mbg.generated
     */
    public void setJournalFilePath(String journalFilePath) {
        this.journalFilePath = journalFilePath == null ? null : journalFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_offset.journal_file_index
     *
     * @return the value of t_journal_offset.journal_file_index
     *
     * @mbg.generated
     */
    public String getJournalFileIndex() {
        return journalFileIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_offset.journal_file_index
     *
     * @param journalFileIndex the value for t_journal_offset.journal_file_index
     *
     * @mbg.generated
     */
    public void setJournalFileIndex(String journalFileIndex) {
        this.journalFileIndex = journalFileIndex == null ? null : journalFileIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_offset.create_time
     *
     * @return the value of t_journal_offset.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_offset.create_time
     *
     * @param createTime the value for t_journal_offset.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_journal_offset.modify_time
     *
     * @return the value of t_journal_offset.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_journal_offset.modify_time
     *
     * @param modifyTime the value for t_journal_offset.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}