package com.clinbrain.model;

import java.util.Date;

public class ParseLogDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restore_data_logdetails.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restore_data_logdetails.logs_id
     *
     * @mbg.generated
     */
    private String logsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restore_data_logdetails.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restore_data_logdetails.err_info
     *
     * @mbg.generated
     */
    private String errInfo;

    public ParseLogDetails() {
    }

    public ParseLogDetails(String errInfo) {
        this.errInfo = errInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restore_data_logdetails.id
     *
     * @return the value of restore_data_logdetails.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restore_data_logdetails.id
     *
     * @param id the value for restore_data_logdetails.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restore_data_logdetails.logs_id
     *
     * @return the value of restore_data_logdetails.logs_id
     *
     * @mbg.generated
     */
    public String getLogsId() {
        return logsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restore_data_logdetails.logs_id
     *
     * @param logsId the value for restore_data_logdetails.logs_id
     *
     * @mbg.generated
     */
    public void setLogsId(String logsId) {
        this.logsId = logsId == null ? null : logsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restore_data_logdetails.create_time
     *
     * @return the value of restore_data_logdetails.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restore_data_logdetails.create_time
     *
     * @param createTime the value for restore_data_logdetails.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restore_data_logdetails.err_info
     *
     * @return the value of restore_data_logdetails.err_info
     *
     * @mbg.generated
     */
    public String getErrInfo() {
        return errInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restore_data_logdetails.err_info
     *
     * @param errInfo the value for restore_data_logdetails.err_info
     *
     * @mbg.generated
     */
    public void setErrInfo(String errInfo) {
        this.errInfo = errInfo == null ? null : errInfo.trim();
    }
}