package com.clinbrain.model;

import java.util.Date;

public class TableMeta {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.ver_id
     *
     * @mbg.generated
     */
    private Integer verId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.ds_id
     *
     * @mbg.generated
     */
    private Integer dsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.column_name
     *
     * @mbg.generated
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.original_column_name
     *
     * @mbg.generated
     */
    private String originalColumnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.column_id
     *
     * @mbg.generated
     */
    private Integer columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.internal_column_id
     *
     * @mbg.generated
     */
    private Integer internalColumnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.hidden_column
     *
     * @mbg.generated
     */
    private String hiddenColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.virtual_column
     *
     * @mbg.generated
     */
    private String virtualColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.original_ser
     *
     * @mbg.generated
     */
    private Integer originalSer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.data_type
     *
     * @mbg.generated
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.data_length
     *
     * @mbg.generated
     */
    private Long dataLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.data_precision
     *
     * @mbg.generated
     */
    private Integer dataPrecision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.data_scale
     *
     * @mbg.generated
     */
    private Integer dataScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.char_length
     *
     * @mbg.generated
     */
    private Long charLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.char_used
     *
     * @mbg.generated
     */
    private String charUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.nullable
     *
     * @mbg.generated
     */
    private String nullable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.is_pk
     *
     * @mbg.generated
     */
    private String isPk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.pk_position
     *
     * @mbg.generated
     */
    private Integer pkPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.alter_time
     *
     * @mbg.generated
     */
    private Date alterTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_table_meta.default_value
     *
     * @mbg.generated
     */
    private String defaultValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.id
     *
     * @return the value of t_table_meta.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.id
     *
     * @param id the value for t_table_meta.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.ver_id
     *
     * @return the value of t_table_meta.ver_id
     *
     * @mbg.generated
     */
    public Integer getVerId() {
        return verId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.ver_id
     *
     * @param verId the value for t_table_meta.ver_id
     *
     * @mbg.generated
     */
    public void setVerId(Integer verId) {
        this.verId = verId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.ds_id
     *
     * @return the value of t_table_meta.ds_id
     *
     * @mbg.generated
     */
    public Integer getDsId() {
        return dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.ds_id
     *
     * @param dsId the value for t_table_meta.ds_id
     *
     * @mbg.generated
     */
    public void setDsId(Integer dsId) {
        this.dsId = dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.table_name
     *
     * @return the value of t_table_meta.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.table_name
     *
     * @param tableName the value for t_table_meta.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.column_name
     *
     * @return the value of t_table_meta.column_name
     *
     * @mbg.generated
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.column_name
     *
     * @param columnName the value for t_table_meta.column_name
     *
     * @mbg.generated
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.original_column_name
     *
     * @return the value of t_table_meta.original_column_name
     *
     * @mbg.generated
     */
    public String getOriginalColumnName() {
        return originalColumnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.original_column_name
     *
     * @param originalColumnName the value for t_table_meta.original_column_name
     *
     * @mbg.generated
     */
    public void setOriginalColumnName(String originalColumnName) {
        this.originalColumnName = originalColumnName == null ? null : originalColumnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.column_id
     *
     * @return the value of t_table_meta.column_id
     *
     * @mbg.generated
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.column_id
     *
     * @param columnId the value for t_table_meta.column_id
     *
     * @mbg.generated
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.internal_column_id
     *
     * @return the value of t_table_meta.internal_column_id
     *
     * @mbg.generated
     */
    public Integer getInternalColumnId() {
        return internalColumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.internal_column_id
     *
     * @param internalColumnId the value for t_table_meta.internal_column_id
     *
     * @mbg.generated
     */
    public void setInternalColumnId(Integer internalColumnId) {
        this.internalColumnId = internalColumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.hidden_column
     *
     * @return the value of t_table_meta.hidden_column
     *
     * @mbg.generated
     */
    public String getHiddenColumn() {
        return hiddenColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.hidden_column
     *
     * @param hiddenColumn the value for t_table_meta.hidden_column
     *
     * @mbg.generated
     */
    public void setHiddenColumn(String hiddenColumn) {
        this.hiddenColumn = hiddenColumn == null ? null : hiddenColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.virtual_column
     *
     * @return the value of t_table_meta.virtual_column
     *
     * @mbg.generated
     */
    public String getVirtualColumn() {
        return virtualColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.virtual_column
     *
     * @param virtualColumn the value for t_table_meta.virtual_column
     *
     * @mbg.generated
     */
    public void setVirtualColumn(String virtualColumn) {
        this.virtualColumn = virtualColumn == null ? null : virtualColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.original_ser
     *
     * @return the value of t_table_meta.original_ser
     *
     * @mbg.generated
     */
    public Integer getOriginalSer() {
        return originalSer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.original_ser
     *
     * @param originalSer the value for t_table_meta.original_ser
     *
     * @mbg.generated
     */
    public void setOriginalSer(Integer originalSer) {
        this.originalSer = originalSer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.data_type
     *
     * @return the value of t_table_meta.data_type
     *
     * @mbg.generated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.data_type
     *
     * @param dataType the value for t_table_meta.data_type
     *
     * @mbg.generated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.data_length
     *
     * @return the value of t_table_meta.data_length
     *
     * @mbg.generated
     */
    public Long getDataLength() {
        return dataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.data_length
     *
     * @param dataLength the value for t_table_meta.data_length
     *
     * @mbg.generated
     */
    public void setDataLength(Long dataLength) {
        this.dataLength = dataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.data_precision
     *
     * @return the value of t_table_meta.data_precision
     *
     * @mbg.generated
     */
    public Integer getDataPrecision() {
        return dataPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.data_precision
     *
     * @param dataPrecision the value for t_table_meta.data_precision
     *
     * @mbg.generated
     */
    public void setDataPrecision(Integer dataPrecision) {
        this.dataPrecision = dataPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.data_scale
     *
     * @return the value of t_table_meta.data_scale
     *
     * @mbg.generated
     */
    public Integer getDataScale() {
        return dataScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.data_scale
     *
     * @param dataScale the value for t_table_meta.data_scale
     *
     * @mbg.generated
     */
    public void setDataScale(Integer dataScale) {
        this.dataScale = dataScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.char_length
     *
     * @return the value of t_table_meta.char_length
     *
     * @mbg.generated
     */
    public Long getCharLength() {
        return charLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.char_length
     *
     * @param charLength the value for t_table_meta.char_length
     *
     * @mbg.generated
     */
    public void setCharLength(Long charLength) {
        this.charLength = charLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.char_used
     *
     * @return the value of t_table_meta.char_used
     *
     * @mbg.generated
     */
    public String getCharUsed() {
        return charUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.char_used
     *
     * @param charUsed the value for t_table_meta.char_used
     *
     * @mbg.generated
     */
    public void setCharUsed(String charUsed) {
        this.charUsed = charUsed == null ? null : charUsed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.nullable
     *
     * @return the value of t_table_meta.nullable
     *
     * @mbg.generated
     */
    public String getNullable() {
        return nullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.nullable
     *
     * @param nullable the value for t_table_meta.nullable
     *
     * @mbg.generated
     */
    public void setNullable(String nullable) {
        this.nullable = nullable == null ? null : nullable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.is_pk
     *
     * @return the value of t_table_meta.is_pk
     *
     * @mbg.generated
     */
    public String getIsPk() {
        return isPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.is_pk
     *
     * @param isPk the value for t_table_meta.is_pk
     *
     * @mbg.generated
     */
    public void setIsPk(String isPk) {
        this.isPk = isPk == null ? null : isPk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.pk_position
     *
     * @return the value of t_table_meta.pk_position
     *
     * @mbg.generated
     */
    public Integer getPkPosition() {
        return pkPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.pk_position
     *
     * @param pkPosition the value for t_table_meta.pk_position
     *
     * @mbg.generated
     */
    public void setPkPosition(Integer pkPosition) {
        this.pkPosition = pkPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.alter_time
     *
     * @return the value of t_table_meta.alter_time
     *
     * @mbg.generated
     */
    public Date getAlterTime() {
        return alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.alter_time
     *
     * @param alterTime the value for t_table_meta.alter_time
     *
     * @mbg.generated
     */
    public void setAlterTime(Date alterTime) {
        this.alterTime = alterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.create_time
     *
     * @return the value of t_table_meta.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.create_time
     *
     * @param createTime the value for t_table_meta.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.comments
     *
     * @return the value of t_table_meta.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.comments
     *
     * @param comments the value for t_table_meta.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_table_meta.default_value
     *
     * @return the value of t_table_meta.default_value
     *
     * @mbg.generated
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_table_meta.default_value
     *
     * @param defaultValue the value for t_table_meta.default_value
     *
     * @mbg.generated
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue == null ? null : defaultValue.trim();
    }
}