package com.clinbrain.mapper;

import com.clinbrain.model.JournalOffset;

import java.util.List;

public interface JournalOffsetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_offset
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_offset
     *
     * @mbg.generated
     */
    int insert(JournalOffset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_offset
     *
     * @mbg.generated
     */
    int insertSelective(JournalOffset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_offset
     *
     * @mbg.generated
     */
    JournalOffset selectByPrimaryKey(Integer id);

    /**
     * get all journal file offset
     * @return
     */
    List<JournalOffset> selectAllJournalOffset();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_offset
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JournalOffset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_journal_offset
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JournalOffset record);
}